# Generated by Django 4.2.3 on 2023-10-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="номер дома"),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Задолженость"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="network_nodes",
                        to="products.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="network.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
    ]
